importCombined();
% plot(TopN, TopicModellingOnly);
% ty = ylabel('F measure');
% set(ty, 'FontSize', 20);
% tx = xlabel('Top n ');
% set(tx, 'FontSize', 20);
% tt = title('F measure vs top n for topic modeling only');
% set(tt, 'FontSize', 20);

% figure;
% plot(TopN, TopicModellingMetadata);
% ty = ylabel('F measure');
% set(ty, 'FontSize', 20);
% tx = xlabel('Top n ');
% set(tx, 'FontSize', 20);
% tt = title('F measure vs top n for topic modeling and Metadata');
% set(tt, 'FontSize', 20);

importTFIDF();
% figure;
% plot(N, FMeasure, 'g');
% ty = ylabel('F measure');
% set(ty, 'FontSize', 20);
% tx = xlabel('Top n ');
% set(tx, 'FontSize', 20);
% tt = title('F measure vs top n for TFIDF only');
% set(tt, 'FontSize', 20);

importHarmonyResults();
% figure;
% plot(n, F1score, 'm');
% ty = ylabel('F measure');
% set(ty, 'FontSize', 20);
% tx = xlabel('Top n ');
% set(tx, 'FontSize', 20);
% tt = title('F measure vs top n for Harmony');
% set(tt, 'FontSize', 20);

figure;
plot(TopN, TopicModellingOnly);
ty = ylabel('F measure');
set(ty, 'FontSize', 20);
tx = xlabel('Top n ');
set(tx, 'FontSize', 20);
tt = title('Comparison of different approaches for NACC');
set(tt, 'FontSize', 20);
hold on;
plot(TopN, TopicModellingMetadata, 'r');
hold on;
plot(N, FMeasure, 'g');
hold on;
plot(n, F1score, 'm');
legend('TopicModelling Only', 'TopicModelling and Metadata', 'TFIDF', 'Harmony');

importLaadc();
importINDD();
importGaain();
FTM_gaain = FTM_gaain(2:end,1);
F_gaain = F_gaain(2:end,1);
N = N(2:end,1);

figure;
tfidfLAADC();
ty = ylabel('F measure');
set(ty, 'FontSize', 20);
tx = xlabel('Top n ');
set(tx, 'FontSize', 20);
tt = title('Comparison of approaches for LAADC');
set(tt, 'FontSize', 20);
hold on;
plot(N, TM_laadc, '-.g');
hold on;
plot(N, F_laadc, '-b');
hold on;
plot(N,tfidf_F_laadc, '--r');
hold on;
legend('TM-Laadc', 'TM+MD-Laadc', 'TFIDF+MD-Laadc');
hold off;

figure;
tfidfINDD();
ty = ylabel('F measure');
set(ty, 'FontSize', 20);
tx = xlabel('Top n ');
set(tx, 'FontSize', 20);
tt = title('Comparison of approaches for INDD');
set(tt, 'FontSize', 20);
hold on;
plot(N, FTM_indd, '-.g');
hold on;
plot(N, F_indd, '-b');
hold on;
plot(N,indd_F_tfidf, '--r');
hold on;
legend('TM-Indd', 'TM+MD-Indd', 'TFIDF+MD-Indd');
hold off;

figure;
tfidfGaain();
ty = ylabel('F measure');
set(ty, 'FontSize', 20);
tx = xlabel('Top n ');
set(tx, 'FontSize', 20);
tt = title('Comparison of approaches for GAAIN');
set(tt, 'FontSize', 20);
hold on;
plot(N, FTM_gaain, '-.g');
hold on;
plot(N, F_gaain, '-b');
hold on;
plot(N, tfidf_F_gaain, '--r')
legend('TM-Gaain', 'TM+MD-Gaain', 'TFIDF+MD-Gaain');
hold off;
